"use client";

import store from "@/redux/store";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import Loading from "@/Components/Loading/Loading";
import {useSelector} from "react-redux"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tic-Tac-Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <title>Tic-Tac-Toe</title>
      <Provider store={store}>
        <body className={inter.className}><Loading/>{children}</body>
      </Provider>
    </html>
  );
}
